---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: ssd
    namespace: monitoring
provisioner: kubernetes.io/gce-pd
parameters:
    type: pd-ssd
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheusvolclaim
  namespace: monitoring
spec:
  storageClassName: ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: prom-svc
  namespace: monitoring
spec:
  selector:
    app: prometheus-server
  ports:
  - protocol: "TCP"
    port: 9090
    targetPort: 9090
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus-ss
  namespace: monitoring
  labels:
    app: prometheus-server
spec:
  serviceName: prom-svc
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-server
  template:
    metadata:
      labels:
        app: prometheus-server
    spec:
      initContainers:
       - name: prometheus-data-permission-fix
         image: busybox
         command: ["/bin/chmod","-R","777", "/data"]
         volumeMounts:
          - name: prometheus-storage-volume
            mountPath: /data
      containers:
        - name: prometheus
          image: prom/prometheus
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/
            - name: prometheus-storage-volume
              mountPath: /prometheus/data/
      volumes:
        - name: prometheus-config-volume
          configMap:
            defaultMode: 420
            name: prometheus-server-conf
  
        - name: prometheus-storage-volume
          persistentVolumeClaim:
            claimName: prometheusvolclaim
